/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zarroboogs_weibo_auth_BeeboAuthUtils */

#ifndef _Included_org_zarroboogs_weibo_auth_BeeboAuthUtils
#define _Included_org_zarroboogs_weibo_auth_BeeboAuthUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getAppKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getAppKey
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getAppSecret
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getRedirectUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getRedirectUrl
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getHackAppKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getHackAppKey
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getHackAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getHackAppSecret
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getHackRedirectUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getHackRedirectUrl
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getHackPackageName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getHackPackageName
  (JNIEnv *, jclass);

/*
 * Class:     org_zarroboogs_weibo_auth_BeeboAuthUtils
 * Method:    getHackKeyHash
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zarroboogs_weibo_auth_BeeboAuthUtils_getHackKeyHash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
