package org.zarroboogs.weibo.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "atusers_table".
 */
public class Green_AtUsersBean implements java.io.Serializable {

    private String accountid;
    private String userid;
    private String at_user_info_json;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Green_AtUsersBean() {
    }

    public Green_AtUsersBean(String accountid, String userid, String at_user_info_json) {
        this.accountid = accountid;
        this.userid = userid;
        this.at_user_info_json = at_user_info_json;
    }

    public String getAccountid() {
        return accountid;
    }

    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getAt_user_info_json() {
        return at_user_info_json;
    }

    public void setAt_user_info_json(String at_user_info_json) {
        this.at_user_info_json = at_user_info_json;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
